name: dart_get_up_to_speed
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  meta: ^1.14.0
  riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
# path: ^1.8.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
